security:
    password_hashers:
<<<<<<< HEAD
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Replace with your actual provider (e.g., entity provider from database)
        users_in_database:
=======
        App\Entity\User:
            algorithm: bcrypt
            cost: 13 # Must match your existing hashes

    providers:
        app_user_provider:
>>>>>>> origin/GestionCommandes
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
<<<<<<< HEAD
            lazy: true
            provider: users_in_database  # Use your actual user provider (could be in-memory, database, etc.)
            
            # Replace the default form_login with your custom authenticator
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                # You may optionally add a target_url for redirection after logout
                # target: app_home

    access_control:
        - { path: ^/user/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        # Add more paths for other roles if needed, e.g., admin routes
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
=======
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            logout:
                path: app_logout
                # Optional: Add a redirect after logout
                target: app_login   
>>>>>>> origin/GestionCommandes
