security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 13 # Must match your existing hashes

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            logout:
                path: app_logout
                # Optional: Add a redirect after logout
                target: app_login   
