# Configuration de base
twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_5_layout.html.twig']

# Configuration spécifique pour l'environnement de test
# (à mettre dans config/packages/test/twig.yaml)
when@test:
    twig:
        strict_variables: true