controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

statistics_bundle:
    resource:
        path: ../src/Bundle/StatisticsBundle/Controller/
        namespace: App\Bundle\StatisticsBundle\Controller
    type: attribute


