parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    twilio_sid: '%env(TWILIO_SID)%'
    twilio_token: '%env(TWILIO_TOKEN)%'
    twilio_from: '%env(TWILIO_FROM)%'
    google_calendar_id: '%env(GOOGLE_CALENDAR_ID)%'
    # Use absolute path to eliminate any path resolution issues
    google_credentials_path: 'C:\Users\msi\Noujoum-Symfony\config\google\credentials.json'


services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicit service definition for SmsService
    App\Service\SmsService:
        arguments:
            $twilio_sid: '%twilio_sid%'
            $twilio_token: '%twilio_token%'
            $twilio_from: '%twilio_from%'
            
    App\Service\GoogleCalendarService: ~
