parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    google_calendar_id: '%env(GOOGLE_CALENDAR_ID)%'
    # Use absolute path to eliminate any path resolution issues
    google_credentials_path: 'C:\Users\msi\Noujoum-Symfony\config\google\credentials.json'

services:
    _defaults:
        autowire: true      # Only for objects
        autoconfigure: true # Only for objects

    # Explicit service definition with absolute paths
    App\Service\GoogleCalendarService:
        arguments:
            $googleCredentials: '%google_credentials_path%'
            $googleCalendarId: '%google_calendar_id%'

    # Other services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'